        
// Types.swift
// Auto-generated by SwiftParse
// See https://github.com/Fleli/SwiftParse

internal typealias TopLevelStatements = [TopLevelStatement]

internal typealias Types = [Type]

internal enum TopLevelStatement: CustomStringConvertible {
	
	case functionDeclaration(FunctionDeclaration)
	
	internal var description: String {
		switch self {
		case .functionDeclaration(let functionDeclaration): return functionDeclaration.description
		}
	}
	
}
internal class FunctionDeclaration: CustomStringConvertible {
	
	let name: String
	let `in`: `Type`
	let out: `Type`
	
	init(_ name: String, _ `in`: `Type`, _ out: `Type`) {
		self.name = name
		self.`in` = `in`
		self.out = out
	}

	internal var description: String {
		"function " + name.description + " " + "func " + `in`.description + " " + "-> " + out.description + " "
	}
	
}
internal indirect enum `Type`: CustomStringConvertible {
	
	case builtin(_ _intunderscore_terminalunderscore_terminal: String)
	case pointer(_ ptr: String, _ _leftParenthesisunderscore_: String, _ type: `Type`, _ _rightParenthesisunderscore_: String)
	case tuple(_ tuple: String, _ _leftSquareBracketunderscore_: String, _ types: Types, _ _rightSquareBracketunderscore_: String)
	case function(_ `func`: String, _ type: `Type`, _ _hyphenunderscore_greaterThanunderscore_: String, _ type1: `Type`)
	
	internal var description: String {
		switch self {
		case .builtin(let _intunderscore_terminalunderscore_terminal): return _intunderscore_terminalunderscore_terminal 
		case .pointer(let ptr, let _leftParenthesisunderscore_, let type, let _rightParenthesisunderscore_): return ptr + _leftParenthesisunderscore_ + type.description + _rightParenthesisunderscore_ 
		case .tuple(let tuple, let _leftSquareBracketunderscore_, let types, let _rightSquareBracketunderscore_): return tuple + _leftSquareBracketunderscore_ + types.description + _rightSquareBracketunderscore_ 
		case .function(let `func`, let type, let _hyphenunderscore_greaterThanunderscore_, let type1): return `func` + type.description + _hyphenunderscore_greaterThanunderscore_ + type1.description 
		}
	}
	
}
